title: East Asian-Australasian Flyway Shorebird Tracking Group
baseURL: https://trackeaaf.netlify.app/
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: My blog
    weight: 1
  fr:
    contentDir: content/fr
    title: Mon blogue
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  background_color_class: bg-black
  description: Welcome to the website of the EAAF Shorebird Tracking Group
  facebook: ''
  favicon: ''
  featured_image:''
  github: ''
  gitlab: ''
  instagram: ''
  linkedin: ''
  mastodon: ''
  recent_posts_number: 1
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: ''
  youtube: ''
